apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: configmgr-rss-ci-cd
spec:
  schedule: "0 8 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: configmgr-rss
            image: masyan.azurecr.io/masyanru/configmgr-rss
          imagePullSecrets:
          - name: masyancr
          restartPolicy: OnFailure
fthfhg
